config/routes.rb
Rails.application.routes.draw do
  root 'tickets#index'
  get 'resolved/tickets', to: 'tickets#resolved'
  get 'admin',to: 'users#admin'
  get 'comments/:id/edit', to: 'comments#edit'
  post 'tickets/:id/comments/:id/edit', to: 'comments#update'
  delete 'comments/:id/destroy', to: 'comments#destroy'
  resource :session
  resources :users

  resources :tickets do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ticket
  belongs_to :user

  validates :body, length: {minimum: 8}
  CURRENTSTATUS = %w(Unverified Verified Development Q.A. Resolved)
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_ticket, except: :show
  before_action :require_signin

  def create
    @comment = @ticket.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save(comment_params)
      log_event(@comment, "Created ")
      @ticket.status = @comment.currentstatus
      @ticket.save
      if @comment.currentstatus == "Resolved"
        @message = "Ticket Closed."
      else
        @message = "Successfully Updated."
      end
      redirect_to ticket_path(@ticket), notice: @message
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @comments =  Comment.where(ticket_id: @comment.ticket_id)
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.save
      if @comment.currentstatus == "Resolved"
        @message = "Ticket Closed."
      else
        @message = "Successfully Updated."
      end
      log_event(@comment, "Updated ")
      redirect_to :admin, notice: @message
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    log_event(@comment, "Deleted ")
    if @comment.destroy
      redirect_to :admin, alert: "Deletion Logged."
    end
  end

private
  def comment_params
    params.require(:comment).permit(:body, :user_id, :ticket_id, :currentstatus)
  end

  def set_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%=form_with model: @ticket.comments, method: :post, url:ticket_comments_path(@ticket) do |form|%>
  <%=form.label "Current Status"%><br>
  <%=form.select :currentstatus, Comment::CURRENTSTATUS, :selected => @ticket.status, class:"linkbutton" %><br>
  <%=form.hidden_field :ticket_id, value: @ticket.id%>
  <%=form.label "Additional Info"%><br>
  <%=form.text_area :body%><br>
  <br>

  <%=form.submit 'Update Ticket'%>

<%end%>

app/views/comments/_show.html.erb
<% @ticket.comments.each do |c| %>
  <div class="commentline taketicket">
  <span class="commentdeets">
  <div class="linkbutton status <%=c.currentstatus%>"><%=c.currentstatus%></div>
    <%=c.user.name%> (<%=prettytime(c.created_at)%>):
  </span><%= link_to c.body, controller: "comments", action: "edit", id: c, ticket_id: c.ticket_id %><br>
  </div>
  <% end %>

app/views/comments/edit.html.erb
<div id="formdiv">
    <div id="infoheader">
        <h2>Edit Comment.</h2>
    </div>


<%=form_with controller: "comments", action: "update", id: @comment.id, ticket_id: @comment.ticket_id do |form|%>
    <%=form.label "Current Status"%><br>
    <%=form.select :currentstatus, Comment::CURRENTSTATUS, :selected => @comment.currentstatus %><br>
    <%=form.hidden_field :ticket_id, value: @ticket.id%>
    <%=form.label "Additional Info"%><br>
    <%=form.text_area :body, value: @comment.body%><br>
    <br>
  
    <%=form.submit 'Update Comment'%>
  
  <%end%>

    <%= link_to 'Cancel Edit', ticket_path(@comment.ticket_id), class: "linkbutton" %>
    <br><br>
    <% if current_user_admin? %>

    <%= link_to 'Delete Comment', ticket_comment_path, method: :delete, class: "linkbutton warning"%>
    <% end %>
</div>

<div id="infodiv">
    <div class="card">
    <div id="infoheader">
    <h2>All Ticket Comments.</h2>
    </div>
    <% @comments.each do |c|%>
        <span class="commentdeets">
        <div class="linkbutton status <%=c.currentstatus%>"><%=c.currentstatus%></div>
          <%=c.user.name%> (<%=prettytime(c.created_at)%>):
        </span> <%= c.body%><br>
    <% end%>
    </div>
</div>