config/routes.rb
Rails.application.routes.draw do
  root 'tickets#index'
  get 'resolved/tickets', to: 'tickets#resolved'
  get 'admin',to: 'users#admin'
  get 'comments/:id/edit', to: 'comments#edit'
  post 'tickets/:id/comments/:id/edit', to: 'comments#update'
  delete 'comments/:id/destroy', to: 'comments#destroy'
  resource :session
  resources :users

  resources :tickets do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_attached_file :screenshot, 
    styles: { full: "640x480>", thumb: "160x120>" },
    storage: :cloudinary,
    path: ':id/:style/:filename',
    cloudinary_resource_type: :image  
  has_many :comments, dependent: :destroy
  validates :title, length: { minimum: 8 }
  validates :description, length: { minimum: 32 }
  validates :status, presence: true
  validates_attachment :screenshot,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

  STATUS = %w(Unverified Verified Development Q.A. Resolved)


  def active
    status !=  "Resolved"
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :require_signin


  def index
    @tickets = Ticket.all
  end

  def resolved
    @tickets = Ticket.where(status: "Resolved")
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])
    if @ticket.update(ticket_params)
      log_event(@ticket, "Updated ")
      redirect_to @ticket, notice: "Sucessfully Updated."
    else
      render :edit
    end
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      log_event(@ticket, "Created ")
      redirect_to @ticket, notice: "Ticket created."
    else
      render :new
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    log_event(@ticket, "Deleted ")
    if @ticket.destroy
      redirect_to tickets_path, alert: "Ticket deleted."
    end
  end

private

  def ticket_params
    params.require(:ticket).permit(:title, :description, :status, :assigned_user, :screenshot)
  end

end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for @ticket do |form|%>
    <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2 class="error">
        <%= pluralize(@ticket.errors.count, "error") %> prohibited
        this ticket from being saved:
      </h2>
      <ul>
        <% @ticket.errors.full_messages.each do |m| %>
          <li class="error"><%= m %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%=form.label :title%><br>
<%=form.text_field :title%><br>
<%=form.label :status%><br>
<%=form.select :status, Ticket::STATUS, prompt:" Choose Status ",class:"selectbox" %>
<br>
<% if request.original_url.include? 'edit'%>
    <% if current_user_admin? %>
      <%=form.label :assigned_user %><br>
      <%=form.select :assigned_user, User.all.collect {|u| [ u.name, u.id ] }, include_blank:true, class:"selectbox"%>
      <br>
      <%end%>
<%end%>

<%=form.label :description%><br>
<%=form.text_area :description%><br>
<%=form.label :screenshot, class:"linkbutton"%><br>
<%=form.file_field :screenshot, style:"display:none;"%><br>
<br>
<%=form.submit%>

<%end%>

app/views/tickets/_info.html.erb
<!-- Modal for large screenshot view -->
<div id="imgModal" class="modal">

  <!-- "X" to close modal -->
  <span class="close">&times;</span>

  <!-- Img tag to be filled with content from thumb -->
  <img class="bigimage" id="img">
  <%=link_to "View original size", @ticket.screenshot.url, id:'caption'%>
</div>
<!-- End screenshot modal-->

<div id="infodiv" class="card">
    <div id="infoheader">
        <h2 class="header">Ticket Information: #<%=@ticket.id%></h2>
    </div>
    <ul>
    <li>Created on: <%=prettytime(@ticket.created_at)%></li>
    <% if @ticket.assigned_user %>
      <li>Assigned to: <%= link_to assigned_user_name(@ticket), User.find(@ticket.assigned_user)%></li>
    <% end %>
    <% if @ticket.status != "Resolved"%>
        <li>Current Status: <span class="linkbutton status <%=@ticket.status%>"><%=@ticket.status%></span></li>
    <% end %>
    <% if @ticket.comments.any?%>
    <li>Started work on: <%=prettytime(@ticket.comments.first.created_at)%></li>
    <li>Number of updates: <%=@ticket.comments.all.count%></li>
    <% end %>
    <li>
    <% if @ticket.active %>
        Last Updated: 
    <% else %>
        Closed on:
    <% end %>
    <%=prettytime(@ticket.updated_at)%></li>
    </ul>
    <div id="infopic">
    <% if @ticket.screenshot.file?%>
        <h2>Screenshot:</h2>
        <%=image_tag @ticket.screenshot.url(:full), id:'thumbnail'%>
    <% end %>
    </div>
</div>

<script>
// Modal for large views of screenshot
//first one puts entire modal div into var
var modal = document.getElementById('imgModal');

// grab thumbnail, set it as src for modal image tag
var img = document.getElementById('thumbnail');
var modalImg = document.getElementById("img");
img.onclick = function(){
    modal.style.display = "block";
    modalImg.src = this.src;
}

// get ready to use "X" to close modal
var span = document.getElementsByClassName("close")[0];
span.onclick = function() {
  modal.style.display = "none";
}
</script>

app/views/tickets/edit.html.erb
<%=render 'info'%>
<div id="formdiv">
    <div id="infoheader">
        <h2>Edit Ticket.</h2>
    </div>
    <%=render 'form'%>
    <%= link_to 'Cancel Edit', ticket_path(@ticket), class: "linkbutton" %>
    <br><br>
    <% if current_user_admin? %>
    <%= link_to 'Delete Ticket', ticket_path(@ticket), method: :delete,data: { confirm: 'Are you sure? There is NO UNDO for this action.' }, class: " warning linkbutton" %>
    <% end %>
</div>

app/views/tickets/index.html.erb
<script>
    hideButton("menuindex");
</script>
<div class="ticketlinkdiv">
<h2><%=link_to 'Resolved Tickets.', resolved_tickets_path, class:'pasttickets switcherbutton'%></h2>
</div>
<div class="centering" id="logo">

<h2>Active Tickets.</h2>
</div>
<div class="centering">
<table class="tablebg">
    <thead>
        <th>ID.</th>
        <th>Issue.</th>
        <th>Description.</th>
        <th>Assigned To.</th>
        <th>Status.</th>
    </thead>

    <% @tickets.each do |t|%>
        <% if t.status != "Resolved" %>
        <tr>
            <td><%= link_to t.id, t%></td>
            <td><%= link_to t.title.truncate(25), t %></td>
            <td><%= link_to t.description.truncate(80), t%></td>
            <% if t.assigned_user %>
            <td><%= link_to assigned_user_name(t), User.find(t.assigned_user)%></td>
            <% else %>
            <td> Unassigned </td>
            <% end %>
            <td><%= link_to t.status, t, class: " linkbutton status #{t.status}"%></td>
        </tr>
        <% end %>
    <%end%>
</table>
</div>

app/views/tickets/new.html.erb
<script>
hideButton("menunew");
</script>
<div id="formdiv">
    <div id="infoheader">
        <h2>New Ticket</h2>
    </div>
    <%=render 'form'%>
    <%= link_to 'Cancel New', tickets_path, class: "linkbutton" %>
</div>
<% if @user = current_user %>

  <div>
      <%= render 'users/info'%>
  </div>
<% end %>

app/views/tickets/resolved.html.erb
<script>
    hideButton("menuindex");
</script>
<div class="ticketlinkdiv">
<h2><%=link_to 'Active Tickets.', tickets_path, class:'pasttickets switcherbutton', id:'logo'%></h2>
</div>
<div class="centering">

<h2 class="pasttickets">Resolved Tickets.</h2>
</div>
<div class="centering">
<table class="tablebg">
    <thead>
        <th>ID.</th>
        <th>Issue.</th>
        <th>Closed On.</th>
        <th>Closed By.</th>
    </thead>
    <% @tickets.each do |t|%>
        <tr>
            <td><%= link_to t.id, t%></td>
            <td><%= link_to t.title.truncate(65), t %></td>
            <td><%= prettytime(t.updated_at)%></td>
            <% if t.assigned_user %>
            <td><%= link_to assigned_user_name(t), User.find(t.assigned_user)%></td>
            <% else %>
            <td> Unassigned </td>
            <% end %>
        </tr>
    <%end%>
</table>
</div>

app/views/tickets/show.html.erb
<div id="editticket">
  <%=link_to "Edit Ticket", edit_ticket_path(@ticket), class: "linkbutton" %>
</div>
  <script>
    buildMenu("editticket");
  </script>
  <div class ="card">
    <div id="infoheader" class="wrap">
      <h2><%=@ticket.title%></h2>
    </div>
    <%= prettytime(@ticket.created_at)%> - <%=@ticket.description%>
    <br>
  </div>

<div class="card">

<div id="infoheader" class="wrap">
    <h3>UPDATES:</h3>
  </div>
  <% if !@ticket.assigned_user %>
  <div class="taketicket">
    <%= form_for @ticket, method: :patch do |f|%>
      <%= f.hidden_field :assigned_user, value: current_user.id %>
      <%= f.submit "Take Ticket"%>
    <% end %>
    Nobody has taken this ticket.
  </div>
  <% end %>
  <%=render 'comments/show'%>

</div>

  <%=render 'info'%>
  <div id="formdiv">
  <div id="infoheader">
<h2>Update Ticket:</h2>
</div>
  <%=render 'comments/form'%>
  <%= link_to 'Cancel Comment', tickets_path, class: "linkbutton" %>

</div>