config/routes.rb
Rails.application.routes.draw do
  root 'tickets#index'
  get 'resolved/tickets', to: 'tickets#resolved'
  get 'admin',to: 'users#admin'
  get 'comments/:id/edit', to: 'comments#edit'
  post 'tickets/:id/comments/:id/edit', to: 'comments#update'
  delete 'comments/:id/destroy', to: 'comments#destroy'
  resource :session
  resources :users

  resources :tickets do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flashdiv #{key}") %>
  <% end %>

app/views/layouts/_footer.html.erb
</div>
<footer>
<script>
buildMenu("auth");
buildMenu("admin");
</script>
    <div id="stripe"></div>
    <div style="text-align:center;font-size:14px;">Copyright ©<%= Time.now.strftime("%Y")%> Andrew Palmer. All rights reserved.</div>
    </footer>

app/views/layouts/_header.html.erb
<% if current_user%>
<div class="username"><%=link_to "Logged in as #{current_user.name}", current_user%></div>
<% end %>

<div id="headerdiv">
    <div id="logo">
        <h1>TicketTracker.</h1>
    </div>
    <div id="logobg">
        <%= cl_image_tag "swatter.png" %>
    </div>
    <h3 style="margin-left:41px;">"WHERE BUGS GO TO DIE."</h3>
</div>
<div id="menu">
    <div class="dothings">
    <em id="things">DO THINGS.</em>
    </div>
    <div id="menuindex">
        <%= link_to "Active Tickets", tickets_path, class: "linkbutton" %>
    </div>
    <div id="menunew">
        <%=link_to 'Start a Ticket', new_ticket_path, class: "linkbutton" %>
    </div>
</div>

<div id="stripe"></div>
<div id="bodydiv">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tickettracker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700i|PT+Serif" rel="stylesheet">

    <%= render 'layouts/flashes' %>

    <script>
    /*simple functions to add/ remove buttons from floating righthand menu*/
    function buildMenu(sourcediv) {
    var menudiv = document.getElementById("menu");
    menudiv.appendChild(document.getElementById(sourcediv));
    }
    
    function hideButton(sourcediv) {
    document.getElementById(sourcediv).style.display="none";
    }
    </script>

    </head>
  <body>
  <!-- menu has button for sign-in or sign-out as needed --->
      <% if !current_user %>
      <div id="auth">
          <%= link_to 'Sign In', new_session_path, class: 'linkbutton error' %>
      </div>
      <% else %>
      <div id="auth">
          <%= link_to 'Sign Out', session_path, method: :delete, class: 'linkbutton error' %>
      </div>
      <% end %>
    <!-- end hide sign-in --->


    <!-- admin only buttons -->

    <% if current_user_admin? %>
    <div id="admin">
        <%= link_to 'Admin', admin_path, class: 'linkbutton admin'%>
    </div>
    
    <% end %>
  <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>